### PR TITLE
Extracts keywords from a phrase

### PR DESCRIPTION
**Pull request by simar5244**
using rake-nltk

### CODE REVIEW

**Comment by simar5244** [comment]
github.com/simar5244

**Comment by gauravr397** [comment]
add some para in text =""""  and test run it

**Comment by simar5244** [comment]
@gauravr397 Works effortlessly :)

**Comment by gauravr397** [comment]
ohk do more thing pls update readme file too 
with all the missing projects names

**Comment by simar5244** [comment]
@gauravr397 done

**Pull request merged**
